# Generated by Django 5.2.1 on 2025-05-28 19:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_add_initial_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashflow',
            name='date_of_create',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='comment',
            field=models.TextField(blank=True, null=True),
        )
    ]
