# Generated by Django 5.2.1 on 2025-05-31 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_fix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashflow',
            name='type',
        ),
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='app.type'),
        ),
    ]
